# Generated by Django 2.2.7 on 2019-12-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('schedule', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('student_id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('schedule', models.CharField(max_length=256, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_scheduler.Organization')),
            ],
        ),
    ]
