# Generated by Django 2.2 on 2019-06-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('team_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('share_pre', models.IntegerField(default=0)),
                ('share_aft', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('student_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('q_pre', models.IntegerField(default=0)),
                ('q_aft', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=256, null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.Org')),
            ],
        ),
    ]
