# Generated by Django 2.2 on 2019-06-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('team_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('team_pre', models.IntegerField(default=0)),
                ('team_aft', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('display_name', models.CharField(max_length=256, null=True)),
                ('student_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('qtr_pre', models.IntegerField(default=0)),
                ('qtr_aft', models.IntegerField(default=0)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.Org')),
            ],
        ),
    ]
